mysite/myauth/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView

from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    AboutMeView,
    logout_view,
    MyLogoutView,
    RegisterView,
    FooBarView,
    UsersListView,
    UserDetailsView,
    ProfileUpdateView,
    HelloView
)

app_name = "myauth"

urlpatterns = [
    path(
        'login/',
        LoginView.as_view(
            template_name='myauth/login.html',
            redirect_authenticated_user=True,
        ),
        name='login',
    ),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("hello/", HelloView.as_view(), name="hello"),
    path('cookie/set/', set_cookie_view, name='cookie-set'),
    path('cookie/get/', get_cookie_view, name='cookie-get'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('session/get/', get_session_view, name='get_session'),
    path('session/set/', set_session_view, name='set_session'),
    path('foo-bar/', FooBarView.as_view(), name='foo-bar'),
    path('users/', UsersListView.as_view(), name='users-list'),
    path('users/<int:pk>/', UserDetailsView.as_view(), name='user-details'),
    path("users/<int:pk>/update/", ProfileUpdateView.as_view(), name="profile_update"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from .sitemaps import sitemaps

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('myapiapp.urls')),
    path('blog/', include('blogapp.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

urlpatterns += i18n_patterns(
    path('accounts/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

mysite/myauth/models.py
from django.db import models
from django.contrib.auth.models import User


def avatar_directory_path(instance: "Profile", filename: str) -> str:
    return "profile/profile_{pk}/avatar/{filename}".format(
        pk=instance.user.pk,
        filename=filename,
    )


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    city = models.CharField(max_length=36, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    avatar = models.ImageField(null=True, blank=True, upload_to=avatar_directory_path)

mysite/myauth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class AuthForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Name')
    last_name = forms.CharField(max_length=30, required=False, help_text='Surname')
    date_of_birth = forms.DateField(required=True, help_text='Date of birth')
    city = forms.CharField(max_length=36, required=False, help_text='City')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("user", "city", "date_of_birth", "avatar",)

mysite/myauth/views.py
from random import random
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView
from django.views.decorators.cache import cache_page
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse, HttpRequest, JsonResponse
from django.shortcuts import render, redirect
from .forms import AuthForm, RegisterForm, ProfileForm
from django.contrib.auth.views import LoginView, LogoutView
from .models import Profile
from django.utils.translation import gettext_lazy as _, ngettext


class HelloView(View):
    welcome_message = _('welcome hello world')

    def get(self, request: HttpRequest) -> HttpResponse:
        items_str = request.GET.get('items') or 0
        items = int(items_str)
        products_line = ngettext(
            'one product',
            '{count} products',
            items,
        )
        products_line = products_line.format(count=items)
        return HttpResponse(
            f"<h1>{self.welcome_message}</h1>"
            f"\n<h2>{products_line}</h2>"
        )


class AboutMeView(TemplateView):
    template_name = "myauth/about-me.html"


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'myauth/register.html'
    success_url = reverse_lazy('myauth:about-me')

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response


def login_view(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('/admin/')

        return render(request, 'myauth/login.html')

    username = request.POST['username']
    password = request.POST['password']

    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('/admin/')

    return render(request, 'myauth/login.html', {'error': 'Invalid login credentials'})


def logout_view(request: HttpRequest):
    logout(request)
    return redirect(reverse('myauth:login'))


class MyLogoutView(LogoutView):
    next_page = reverse_lazy('myauth:login')


@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse('Cookie set')
    response.set_cookie('fizz', 'buzz', max_age=3600)
    return response


def another_register_view(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            date_of_birth = form.cleaned_data.get('date_of_birth')
            city = form.cleaned_data.get('city')
            Profile.objects.create(
                user=user,
                city=city,
                date_of_birth=date_of_birth
            )
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = RegisterForm()
    return render(request, 'myauth/register.html', {'form': form})


@cache_page(60 * 2)
def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("fizz", "default value")
    return HttpResponse(f'Cookie value: {value!r} + {random()}')


@permission_required('myauth.view_profile', raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session['foobar'] = 'spameggs'
    return HttpResponse('Session set!')


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get('foobar', 'default')
    return HttpResponse(f'session value: {value!r}')


class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({"foo": "bar", "spam": "eggs"})


class UsersListView(ListView):
    template_name = "myauth/users-list.html"
    context_object_name = "users"
    queryset = User.objects.order_by('pk').all()


class UserDetailsView(DetailView):
    template_name = "myauth/user-details.html"
    model = User
    context_object_name = "user"


class ProfileUpdateView(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = "myauth/profile_update_form.html"

    def test_func(self):
        return self.request.user.is_staff or self.request.user.profile == self.get_object()

    def form_valid(self, form):
        response = super().form_valid(form)
        return response

    def get_success_url(self):
        return reverse(
            "myauth:user-details",
            kwargs={"pk": self.object.user.pk},
        )

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}
{% load cache %}

{% block title %}
  About me
{% endblock %}


{% block body %}
  <h1>User info</h1>
  <div>
    Products available: {% now "u" %}
  </div>
  {% if user.is_authenticated %}
    {% cache 300 userinfo user.username %}
      <h2>Detail</h2>
      <p>Username: {{ user.username }}</p>
      <p>First name: {{ user.first_name }}</p>
      <p>Last name: {{ user.last_name }}</p>
      <p>Email: {{ user.email }}</p>
      <p>Bio: {{ user.profile.bio }}</p>
      {% if user.profile.avatar %}
        <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}">
      {% else %}
        <p>Avatar is not uploaded.</p>
      {% endif %}
      <div>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit"><a href="{% url 'myauth:profile_update' pk=user.pk %}">Update profile</a></button>
        </form>
      </div>
    {% endcache %}
  {% else %}
    <h2>User is anonymous</h2>
  {% endif %}
{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}

  {% endblock %}</title>
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
  Login
{% endblock %}


{% block body %}
    <h2>Авторизация</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>

{% endblock %}

mysite/myauth/templates/myauth/profile_update_form.html
{% extends 'myauth/base.html' %}

{% block title %}
  Update profile
{% endblock %}

{% block body %}
  <h1>Update profile</h1>
  <div>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Update</button>
    </form>
  </div>
  <div>
    <a href="{% url 'myauth:user-details' pk=object.pk %}"
    >Back to user profile #{{ object.pk }}</a>
  </div>
{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
  Регистрация
{% endblock %}


{% block body %}
    <h2>Регистрация</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign up</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/user-details.html
{% extends 'myauth/base.html' %}

{% block title %}
  User #{{ user.pk }}
{% endblock %}

{% block body %}
  <h1>User <strong>{{ user.username }}</strong></h1>
  <div>
    <div>City: {{ user.profile.city }}</div>
    <div>Date_of_birth: {{ user.profile.date_of_birth }}</div>
    {% if user.profile.avatar %}
      <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}">
    {% else %}
      <p>Avatar is not uploaded.</p>
    {% endif %}
  </div>

  <div>
    {% if request.user.is_authenticated and request.user.is_staff or user.profile.user == request.user %}
      <p>You can update the profile by this link.</p>
      <a href="{% url 'myauth:profile_update' pk=user.pk %}">Update profile</a>
    {% else %}
        <p>You don't have permission to update the profile.</p>
    {% endif %}
  </div>

  <div>
    <a href="{% url 'myauth:users-list' %}">Back to users list</a>
  </div>
{% endblock %}

mysite/myauth/templates/myauth/users-list.html
{% extends 'myauth/base.html' %}

{% block title %}
  List of users
{% endblock %}

{% block body %}
  <h1>Users:</h1>
  {% if users %}
    <div>
    {% for user in users %}
      <div>
        <p>Name: <a href="{% url 'myauth:user-details' pk=user.pk %}"
        >{{ user.username }}</a></p>
      </div>
    {% endfor %}
    </div>
  {% else %}
    <h3>No registered users yet</h3>
  {% endif %}
{% endblock %}